package content

import (
	"context"
	"fmt"
	"strings"
	"time"
	"unicode"

	"github.com/Saumya40-codes/systems-daily/internal/llm"
	"github.com/Saumya40-codes/systems-daily/internal/topics"
)

// Article is a generated daily write-up.
type Article struct {
	Topic     topics.Topic
	Subject   string
	Body      string // markdown-ish plain text suitable for email
	WordCount int
	Model     string
	Generated time.Time
}

// Generator builds medium-depth systems write-ups via an LLM.
type Generator struct {
	LLM            *llm.Client
	TargetWordsMin int
	TargetWordsMax int
}

// Generate produces one article for the given topic.
func (g *Generator) Generate(ctx context.Context, topic topics.Topic) (*Article, error) {
	minW := g.TargetWordsMin
	maxW := g.TargetWordsMax
	if minW <= 0 {
		minW = 700
	}
	if maxW <= minW {
		maxW = minW + 400
	}

	body, err := g.LLM.Chat(ctx, systemPrompt(minW, maxW), userPrompt(topic))
	if err != nil {
		return nil, err
	}

	body = cleanBody(body)
	wc := wordCount(body)
	subject := buildSubject(topic, body)

	return &Article{
		Topic:     topic,
		Subject:   subject,
		Body:      body,
		WordCount: wc,
		Model:     g.LLM.Model,
		Generated: time.Now(),
	}, nil
}

func cleanBody(s string) string {
	s = strings.TrimSpace(s)
	// Strip accidental markdown fences wrapping the whole reply
	if strings.HasPrefix(s, "```") {
		lines := strings.Split(s, "\n")
		if len(lines) >= 2 {
			lines = lines[1:]
			if n := len(lines); n > 0 && strings.TrimSpace(lines[n-1]) == "```" {
				lines = lines[:n-1]
			}
			s = strings.TrimSpace(strings.Join(lines, "\n"))
		}
	}
	return s
}

func wordCount(s string) int {
	n := 0
	inWord := false
	for _, r := range s {
		if unicode.IsSpace(r) {
			inWord = false
			continue
		}
		if !inWord {
			n++
			inWord = true
		}
	}
	return n
}

func buildSubject(topic topics.Topic, body string) string {
	// Prefer first markdown H1/H2 if present
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "# ") {
			return "Systems daily: " + strings.TrimSpace(strings.TrimPrefix(line, "# "))
		}
		if strings.HasPrefix(line, "## ") {
			return "Systems daily: " + strings.TrimSpace(strings.TrimPrefix(line, "## "))
		}
	}
	return "Systems daily: " + topic.Title
}

// PlainEmail formats the article for a text/plain email body.
func PlainEmail(a *Article) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", a.Subject)
	fmt.Fprintf(&b, "Category: %s · ~%d words · model: %s · %s\n",
		a.Topic.Category, a.WordCount, a.Model, a.Generated.Format("2006-01-02 15:04 MST"))
	b.WriteString(strings.Repeat("-", 48))
	b.WriteString("\n\n")
	b.WriteString(a.Body)
	b.WriteString("\n\n")
	b.WriteString(strings.Repeat("-", 48))
	b.WriteString("\nGenerated by systems-daily - daily systems reps.\n")
	return b.String()
}
