package content

import (
	"context"
	"fmt"
	"strings"
	"time"
	"unicode"

	"github.com/Saumya40-codes/systems-daily/internal/llm"
	"github.com/Saumya40-codes/systems-daily/internal/topics"
)

// Article is a generated daily write-up.
type Article struct {
	Topic     topics.Topic
	Subject   string
	Body      string // markdown-ish plain text suitable for email
	WordCount int
	Model     string
	Generated time.Time
}

// Generator builds medium-depth systems write-ups via an LLM.
type Generator struct {
	LLM            *llm.Client
	TargetWordsMin int
	TargetWordsMax int
}

// Generate produces one article for the given topic.
func (g *Generator) Generate(ctx context.Context, topic topics.Topic) (*Article, error) {
	minW := g.TargetWordsMin
	maxW := g.TargetWordsMax
	if minW <= 0 {
		minW = 700
	}
	if maxW <= minW {
		maxW = minW + 400
	}

	angles := ""
	if len(topic.Angles) > 0 {
		angles = "Optional focus angles (pick what makes a coherent piece, not a checklist):\n- " +
			strings.Join(topic.Angles, "\n- ")
	}

	system := `You write daily systems engineering deep-dives for a passionate low-level engineer.

Voice:
- Technical, precise, curious - like a sharp blog post or an internal eng note, not a textbook chapter.
- Assume the reader knows C, OS basics, and can read a bit of pseudo-code.
- Prefer concrete mechanics over vague inspiration.
- No corporate fluff, no "in today's fast-paced world", no emojis.

Structure (use plain text with light markdown: ## headers, **bold**, fenced code if useful):
1. A punchy title line (the topic, sharpened).
2. Hook: why this matters in real systems (2-4 sentences).
3. Core mechanics: how it actually works (bulk of the piece).
4. One small worked example, diagram-in-words, or pseudo-code walkthrough.
5. Tradeoffs / footguns practitioners hit.
6. "Go deeper" - 2-3 specific next things to read or try (man pages, papers, kernel paths, RFCs - be concrete).

Length: roughly ` + fmt.Sprintf("%d-%d", minW, maxW) + ` words. Not a tweet thread, not a novella.
If you use code, keep it short (<=20 lines). Prefer insight density over completeness.`

	user := fmt.Sprintf(`Write today's systems deep-dive.

Topic: %s
Category: %s
%s

Output the article body only (no email headers, no subject line, no preamble like "Sure!").`,
		topic.Title, topic.Category, angles)

	body, err := g.LLM.Chat(ctx, system, user)
	if err != nil {
		return nil, err
	}

	body = cleanBody(body)
	wc := wordCount(body)
	subject := buildSubject(topic, body)

	return &Article{
		Topic:     topic,
		Subject:   subject,
		Body:      body,
		WordCount: wc,
		Model:     g.LLM.Model,
		Generated: time.Now(),
	}, nil
}

func cleanBody(s string) string {
	s = strings.TrimSpace(s)
	// Strip accidental markdown fences wrapping the whole reply
	if strings.HasPrefix(s, "```") {
		lines := strings.Split(s, "\n")
		if len(lines) >= 2 {
			lines = lines[1:]
			if n := len(lines); n > 0 && strings.TrimSpace(lines[n-1]) == "```" {
				lines = lines[:n-1]
			}
			s = strings.TrimSpace(strings.Join(lines, "\n"))
		}
	}
	return s
}

func wordCount(s string) int {
	n := 0
	inWord := false
	for _, r := range s {
		if unicode.IsSpace(r) {
			inWord = false
			continue
		}
		if !inWord {
			n++
			inWord = true
		}
	}
	return n
}

func buildSubject(topic topics.Topic, body string) string {
	// Prefer first markdown H1/H2 if present
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "# ") {
			return "Systems daily: " + strings.TrimSpace(strings.TrimPrefix(line, "# "))
		}
		if strings.HasPrefix(line, "## ") {
			return "Systems daily: " + strings.TrimSpace(strings.TrimPrefix(line, "## "))
		}
	}
	return "Systems daily: " + topic.Title
}

// PlainEmail formats the article for a text/plain email body.
func PlainEmail(a *Article) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", a.Subject)
	fmt.Fprintf(&b, "Category: %s · ~%d words · model: %s · %s\n",
		a.Topic.Category, a.WordCount, a.Model, a.Generated.Format("2006-01-02 15:04 MST"))
	b.WriteString(strings.Repeat("─", 48))
	b.WriteString("\n\n")
	b.WriteString(a.Body)
	b.WriteString("\n\n")
	b.WriteString(strings.Repeat("─", 48))
	b.WriteString("\nGenerated by systems-daily - daily systems reps.\n")
	return b.String()
}
